---
- name: Prepare ML Server
  hosts: mlserver
  become: yes
  become_user: deploy
  tasks:
    - name: ping
      shell: pwd >> pwd2.txt
    - name: Pull from Git
      ansible.builtin.git:
        repo: git@github.com:Lemeri02/mlops_practice_4.git
        dest: /home/deploy/mlops_practice_4
        accept_hostkey: true
        key_file: /home/deploy/.ssh/id_ed25519

    - name: create venv
      ansible.builtin.shell: python3 -m venv /home/deploy/mlops_practice_4/venv
      args:
        executable: /bin/bash

    - name: Give insecure permissions to an existing file
      become: yes
      become_user: root
      ansible.builtin.file:
        path: /home/deploy/mlops_practice_4
        owner: deploy
        group: deploy
        recurse: yes

    - name: Install requirements.txt
      become: yes
      become_user: deploy
      ansible.builtin.pip:
        requirements: /home/deploy/mlops_practice_4/requirements.txt
        virtualenv: /home/deploy/mlops_practice_4/venv

    - name: Run venv
      ansible.builtin.shell: source /home/deploy/mlops_practice_4/venv/bin/activate
      args:
        executable: /bin/bash

    - name: Get data
      become: yes
      become_user: root
      script: /home/deploy/mlops_practice_4/scripts/data_scripts/get_data.py
      args:
        executable: /home/deploy/mlops_practice_4/venv/bin/python

    - name: Run DVC repro
      ansible.builtin.shell: 
        cmd: dvc repro
        chdir: /home/deploy/mlops_practice_4

  vars:
    ansible_ssh_pass: "{{ lookup('env', 'DEPLOY_PASSWORD') }}"
    ansible_become_pass: "{{ lookup('env', 'DEPLOY_PASSWORD') }}"





      # shell: python3 /home/deploy/mlops_practice_4/scripts/data_scripts/get_data.py
# - name: Download Dataset
#   hosts: mlserver
#   become: yes
#     tasks:
#     - name: download dataset
#       shell: pwd >> pwd2.txt



# ---
# - name: Test PING
#   hosts: all
#   become: true
#   tasks:
#     - name: ping
#       user:
#         name: deploy
#         password: 3480916
#       # set_fact:
#       #   provider:
#       #     username: deploy
#       #     password: 3480916
#       #     auth_pass: "{{ ansible_become_pass }}"
#     - name: Hello
#       ios_command:
#         # provider: "{{ provider }}"
#         shell: pwd >> pwd.txt

