---
- name: Test PING
  hosts: all
  become: yes
  tasks:
    - name: ping
      shell: pwd >> pwd2.txt
  vars:
    ansible_ssh_pass: "{{ lookup('env', 'DEPLOY_PASSWORD') }}"
    ansible_become_pass: "{{ lookup('env', 'DEPLOY_PASSWORD') }}"

# ---
# - name: Test PING
#   hosts: all
#   become: true
#   tasks:
#     - name: ping
#       user:
#         name: deploy
#         password: 3480916
#       # set_fact:
#       #   provider:
#       #     username: deploy
#       #     password: 3480916
#       #     auth_pass: "{{ ansible_become_pass }}"
#     - name: Hello
#       ios_command:
#         # provider: "{{ provider }}"
#         shell: pwd >> pwd.txt

